name: My First CI workflow

on: [push]

jobs:
  build:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: pip3 install requests
      - name: Run
        run: python3.6 app.py
