name: My First CI workflow

on:
  push:
    branches: [master]

jobs:
  build:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Observe current directory
        run: ls -a && pwd
      - name: Find scripts
        run: find /home -name "*.py"
      - name: Install deps
        run: pip3 install requests
      - name: Run
        run: python3.6 app.py
